# Set username, password, and host in .env.local
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    env_file:
      - .env.local
    ports:
      - 3306:3306
    volumes:
      - ./db_files:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
